-- MySQL Script generated by MySQL Workbench
-- Sun Jan 12 16:36:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `movies` ;

-- -----------------------------------------------------
-- Schema movies
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movies` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `movies` ;

-- -----------------------------------------------------
-- Table `movies`.`pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`pelicula` (
  `id_pelicula` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `año` YEAR NOT NULL,
  `duracion` INT NULL DEFAULT NULL,
  `sinopsis` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pelicula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`calificaciones` (
  `id_calificacion` INT NOT NULL AUTO_INCREMENT,
  `id_pelicula` INT NOT NULL,
  `puntaje` DECIMAL(3,1) NOT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_calificacion`),
  INDEX `id_pelicula` (`id_pelicula` ASC) VISIBLE,
  CONSTRAINT `calificaciones_ibfk_1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `movies`.`pelicula` (`id_pelicula`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`coleccion` (
  `id_coleccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_coleccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`compania_de_produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`compania_de_produccion` (
  `id_compañia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_compañia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`genero` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`idioma` (
  `id_idioma` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_idioma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`pais_de_produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`pais_de_produccion` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`pelicula_coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`pelicula_coleccion` (
  `id_pelicula` INT NOT NULL,
  `id_coleccion` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_coleccion`),
  INDEX `id_coleccion` (`id_coleccion` ASC) VISIBLE,
  CONSTRAINT `pelicula_coleccion_ibfk_1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `movies`.`pelicula` (`id_pelicula`),
  CONSTRAINT `pelicula_coleccion_ibfk_2`
    FOREIGN KEY (`id_coleccion`)
    REFERENCES `movies`.`coleccion` (`id_coleccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`pelicula_compania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`pelicula_compania` (
  `id_pelicula` INT NOT NULL,
  `id_compañia` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_compañia`),
  INDEX `id_compañia` (`id_compañia` ASC) VISIBLE,
  CONSTRAINT `pelicula_compania_ibfk_1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `movies`.`pelicula` (`id_pelicula`),
  CONSTRAINT `pelicula_compania_ibfk_2`
    FOREIGN KEY (`id_compañia`)
    REFERENCES `movies`.`compania_de_produccion` (`id_compañia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`pelicula_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`pelicula_genero` (
  `id_pelicula` INT NOT NULL,
  `id_genero` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_genero`),
  INDEX `id_genero` (`id_genero` ASC) VISIBLE,
  CONSTRAINT `pelicula_genero_ibfk_1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `movies`.`pelicula` (`id_pelicula`),
  CONSTRAINT `pelicula_genero_ibfk_2`
    FOREIGN KEY (`id_genero`)
    REFERENCES `movies`.`genero` (`id_genero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`pelicula_idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`pelicula_idioma` (
  `id_pelicula` INT NOT NULL,
  `id_idioma` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_idioma`),
  INDEX `id_idioma` (`id_idioma` ASC) VISIBLE,
  CONSTRAINT `pelicula_idioma_ibfk_1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `movies`.`pelicula` (`id_pelicula`),
  CONSTRAINT `pelicula_idioma_ibfk_2`
    FOREIGN KEY (`id_idioma`)
    REFERENCES `movies`.`idioma` (`id_idioma`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`pelicula_pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`pelicula_pais` (
  `id_pelicula` INT NOT NULL,
  `id_pais` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_pais`),
  INDEX `id_pais` (`id_pais` ASC) VISIBLE,
  CONSTRAINT `pelicula_pais_ibfk_1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `movies`.`pelicula` (`id_pelicula`),
  CONSTRAINT `pelicula_pais_ibfk_2`
    FOREIGN KEY (`id_pais`)
    REFERENCES `movies`.`pais_de_produccion` (`id_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `movies`.`pelicula_persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies`.`pelicula_persona` (
  `id_pelicula` INT NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`, `id_persona`),
  INDEX `id_persona` (`id_persona` ASC) VISIBLE,
  CONSTRAINT `pelicula_persona_ibfk_1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `movies`.`pelicula` (`id_pelicula`),
  CONSTRAINT `pelicula_persona_ibfk_2`
    FOREIGN KEY (`id_persona`)
    REFERENCES `movies`.`persona` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
